[package]
name = "dissertation"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = [
    "std",
    "serde",
] }
csv = "1.3.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_with = "3.4.0"
thiserror = "1.0.50"
