[package]
name = "irdis"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition", "--cfg", "docsrs"]

[workspace]
members = ["irdis-branch-bound", "irdis-instance"]
